### ISSUE TITLE
Broken Modules

### ISSUE THREAD

**Issue by Lovingtaken3** [cxstudios-llc/aurora-theme#3]
Vote, suggestions, Socialize, and Newsletter are currently broken.
<img width="188" alt="newsletter" src="https://github.com/cxstudios-llc/aurora-theme/assets/17980552/ac90c61f-200d-4af2-be75-8770d4b95f80">

**Comment by bijju089** [comment]
Vote, Suggestions, Newletter module are supported. Looks like you have done something wrong there.
You can update to https://github.com/cxstudios-llc/aurora-theme/releases/tag/v0.9 for module support and improvements.
Socialize module is outdated and not supported on v2.1.2
